name: rsync
on: 
  schedule:
  - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  m-od-p1-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_CONF_PASS: ${{ secrets.RCLONE_CONF_PASS }}
      with:
        args: sync m-od:/ p1-sueice:/m-od/ --progress --stats-one-line-date

  r1-od-p1-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_CONF_PASS: ${{ secrets.RCLONE_CONF_PASS }}
      with:
        args: sync r1-od:/ p1-sueice:/r1-od/ --progress --stats-one-line-date
