name: rsync
on: 
  schedule:
  - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  p1-backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_CONF_PASS: ${{ secrets.RCLONE_CONF_PASS }}
      with:
        args: sync p1-sueice:/ r-transfer:/p1-backup/

  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
