name: rsync
on: 
  schedule:
  - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  drive-r3od-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_CONF_PASS: ${{ secrets.RCLONE_CONF_PASS }}
      with:
        args: sync dsb-drive:/ r3-od:/Drive/ --stats-one-line-date
        
  mod-acthdrive-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
        RCLONE_CONF_PASS: ${{ secrets.RCLONE_CONF_PASS }}
      with:
        args: sync m-od:/ acth-drive:/mod/ --stats-one-line-date

  drive-r3od-clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      env: 
        RCLONE_CONF: ${{ secrets.RCLONE_CONFIG }}
      with:
       args: cleanup r3-od:/Drive
